//
//  HistoryView.swift
//  BabyFoodTracker
//
//  Created by Sophia Tang on 7/2/25.
//

// This file defines the view for displaying food history.

import SwiftUI

struct HistoryView: View {
    @ObservedObject var foodStore: FoodDataStore
    @State private var selectedDate: Date = Date()

    var body: some View {
        NavigationView {
            VStack {
                // Calendar View (Placeholder, complex calendar component to be generated by AI)
                Text("Calendar View (To be implemented)")
                    .font(.largeTitle)
                    .padding()
                    .foregroundColor(.gray)

                // Simple list to display entries for the selected day
                List {
                    ForEach(foodStore.entries.filter { Calendar.current.isDate($0.date, inSameDayAs: selectedDate) }) { entry in
                        HStack {
                            VStack(alignment: .leading) {
                                Text(entry.foodContent)
                                    .font(.headline)
                                Text(entry.date, style: .time)
                                    .font(.subheadline)
                                    .foregroundColor(.gray)
                            }
                            Spacer()
                            if let photoData = entry.photoData, let uiImage = UIImage(data: photoData) {
                                Image(uiImage: uiImage)
                                    .resizable()
                                    .scaledToFill()
                                    .frame(width: 50, height: 50)
                                    .clipShape(Circle())
                            }
                        }
                    }
                    .onDelete(perform: foodStore.deleteEntry) // Add delete functionality
                }
                .navigationTitle("Food History")
                .navigationBarTitleDisplayMode(.inline)
            }
        }
    }
}

struct HistoryView_Previews: PreviewProvider {
    static var previews: some View {
        HistoryView(foodStore: FoodDataStore())
    }
}
